version: '4.4'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: electronic-diary
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dairy-network

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    networks:
#      - task-network

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#    networks:
#      - task-network

  diary-service:
    build:
      context: ./diary-server
    container_name: diary-service
    env_file:
      - .env
    depends_on:
      - postgres
#      - kafka
#      - zookeeper
    environment:
      USER_SERVICE_URL: http://user-service:8081
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - dairy-network

#  notification-service:
#    build:
#      context: ./notification-service
#    container_name: notification-service
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - kafka
#      - zookeeper
#    environment:
#      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    ports:
#      - "8082:8082"
#    networks:
#      - task-network
#
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - .env
    depends_on:
      - postgres
#      - kafka
#      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8081:8081"
    networks:
      - dairy-network

volumes:
  postgres-data:

networks:
  dairy-network:
    driver: bridge

